require space between commit author name and email, for Git compatibility
Allowing such author fields breaks 'got send' towards Github for affected
commits because git-index-pack --strict will error out on the server:

$ git index-pack --strict pack-de791fb6a3a1961e44ac5d98d72fd533bf9277c8.pack
error: object 5d6bde9eaaf27f41ae8fa7112bb45e489d3c16b9: missingSpaceBeforeEmail:
    invalid author/committer line - missing space before email
fatal: fsck error in packed object

problem encountered by landry@
ok op@