revert previous commit to sync with diff.git changes; it broke the build
../lib/blame.c:344:11: error: implicit declaration of function 'diff_atom_hash_update'