sterror: use XPG version on GLIBC
It looks like autoconf 2.69 will not provide XPG strerror_r even
if the appropriate macros are set which request the XPG version.

Until this is fixed in autoconf and that version is more widely-adopted,
this approach will provide what's required.

Originally from Stefan Sperling, tweaked by me.