remove casts which make older gcc versions unhappy
../lib/diffreg.c:44: error: initializer element is not constant
../lib/diffreg.c:51: error: initializer element is not constant
../lib/diffreg.c:59: error: initializer element is not constant
../lib/diffreg.c:66: error: initializer element is not constant

reported by Red on Libera IRC, and by sthen@ who pointed out such
failures appearing in landry's sparc64 bulk build logs.